name: key_budget
description: "KeyBudget Project"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite_sqlcipher: ^3.2.1
  flutter_secure_storage: ^10.0.0-beta.4
  encrypt: ^5.0.3
  path_provider: ^2.1.2
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  path: ^1.9.0
  fl_chart: ^1.0.0
  image_picker: ^1.1.2
  local_auth: ^2.2.0
  permission_handler: ^12.0.1
  file_saver: ^0.3.1
  file_picker: ^10.3.1
  csv: ^6.0.0
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"
