name: key_budget
description: "Key Budget"
publish_to: 'Vinicius'
version: 4.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.2.0

  # State Management
  provider: ^6.1.5

  # Core & Services
  flutter_dotenv: ^6.0.0
  encrypt: ^5.0.3
  intl: ^0.20.2
  path: ^1.9.1
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3

  # UI & UX
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  fl_chart: ^1.0.0
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  photo_view: ^0.15.0

  # Forms & Input
  flutter_masked_text2: ^0.9.1
  mask_text_input_formatter: ^2.9.0

  # Authentication
  local_auth: ^2.3.0
  local_auth_android: ^1.0.38
  google_sign_in: ^6.1.6
  googleapis: ^15.0.0

  # File Handling
  image_picker: ^1.2.0
  file_picker: ^10.3.1
  file_saver: ^0.3.1
  csv: ^6.0.0
  open_file: ^3.3.2
  share_plus: ^12.0.0

  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^31.1.21

  # Others
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/