name: key_budget
description: "KeyBudget Project"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite_sqlcipher: ^2.1.0
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  path_provider: ^2.1.2
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  path: ^1.9.0
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  local_auth: ^2.2.0
  permission_handler: ^11.3.1
  file_saver: ^0.3.1
  file_picker: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
