name: key_budget
description: "Key Budget"
publish_to: 'Vinicius'
version: 2.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  provider: ^6.1.5
  flutter_dotenv: ^6.0.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  intl: ^0.20.2
  path: ^1.9.1
  connectivity_plus: ^6.1.5
  flutter_secure_storage: ^10.0.0-beta.4
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.2
  fl_chart: ^1.0.0
  image_picker: ^1.2.0
  file_picker: ^10.3.1
  file_saver: ^0.3.1
  csv: ^6.0.0
  permission_handler: ^12.0.1
  local_auth: ^2.3.0
  flutter_launcher_icons: ^0.14.4
  google_sign_in: ^6.1.6
  flutter_masked_text2: ^0.9.1
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  local_auth_android: ^1.0.28
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/.env
    - assets/icon/
    - assets/data/


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"